### ISSUE TITLE
Open Source It

### ISSUE THREAD

**Issue by Siecje** [bentranter/default#4]
It needs a license for it to be Open Source!

I recommend CC0 for this repo and MIT for your CSS since that is what BassCSS uses.

With the CC0 license you wouldn't have to keep the license file after you cloned the repo.

https://creativecommons.org/choose/zero/

**Comment by bentranter** [comment]
Whoops, I used to be good about this but I've been forgetting a lot lately. I think I like CC0 better than MIT cause of that, so I'll go with it. This has also really diverged from BassCSS, so I'm not sure about how that works for licensing, but I'll look into it

**Comment by bentranter** [comment]
Also, leaving this open until I figure out how to handle the CSS licensing, since the CSS is getting pretty far from the original BassCSS

**Comment by Siecje** [comment]
Well to use BassCSS you need MIT.

I would use MIT anyways, unless you are worried about someone using your name to endorse their product than you could use BSD with the 3 clauses.

**Comment by bentranter** [comment]
It's easier just to use MIT, so unless I end up re-writing the CSS from scratch, I'll stick with that.
